# Generated by Django 6.0 on 2026-01-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='generation',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', '수강생'), ('staff', '운영진')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
