# Generated by Django 6.0 on 2026-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='understandingcheck',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='understandingcheck',
            name='target_response_count',
            field=models.IntegerField(default=20, help_text='목표 응답 인원'),
        ),
    ]
