# Generated by Django 5.2.9 on 2026-01-05 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("live_sessions", "0002_alter_livesession_id_alter_livesessionmember_id"),
        ("questions", "0002_alter_comment_id_alter_like_id_alter_question_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="LiveLiveSession",
            new_name="LiveSession",
        ),
        migrations.RemoveField(
            model_name="question",
            name="timing",
        ),
        migrations.CreateModel(
            name="UnderstandingCheck",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="understanding_checks",
                        to="live_sessions.livesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnderstandingResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "understanding_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="questions.understandingcheck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("understanding_check", "user")},
            },
        ),
    ]
