# Generated by Django 5.2.9 on 2026-01-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_livelivesession_question_live_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='timing',
        ),
    ]
