# Generated by Django 6.0 on 2026-01-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesessionmember',
            name='nickname',
            field=models.CharField(default='익명', max_length=50),
        ),
    ]
